### ISSUE TITLE
Fink client updates

### ISSUE THREAD

**Issue by JulienPeloton** [grandma-collaboration/icare#97]
Syntax for the fink-client has changed -- and the code crashes:

```
Traceback (most recent call last):
  File "/pdisk/htdocs/skyportal/deployment/grandma_skyportal/patched_skyportal/services/fink/fink.py", line 87, in <module>
    skyportal_fink_client()
  File "/pdisk/htdocs/skyportal/deployment/grandma_skyportal/patched_skyportal/services/fink/fink.py", line 83, in skyportal_fink_client
    skyportalfinkclient.poll_alerts(**fink_config, log=log)
  File "/pdisk/htdocs/skyportal/deployment/grandma_skyportal/patched_skyportal/services/fink/skyportal-fink-client/skyportal_fink_client/skyportal_fink_client.py", line 382, in poll_alerts
    consumer = init_consumer(
  File "/pdisk/htdocs/skyportal/deployment/grandma_skyportal/patched_skyportal/services/fink/skyportal-fink-client/skyportal_fink_client/skyportal_fink_client.py", line 195, in init_consumer
    consumer = AlertConsumer(topics=fink_topics, config=fink_config)
  File "/pdisk/anaconda/envs/skyportal/lib/python3.10/site-packages/fink_client/consumer.py", line 76, in __init__
    self._kafka_config = _get_kafka_config(config)
  File "/pdisk/anaconda/envs/skyportal/lib/python3.10/site-packages/fink_client/consumer.py", line 524, in _get_kafka_config
    kafka_config["group.id"] = config["group.id"]
KeyError: 'group.id'

```

**Comment by JulienPeloton** [comment]
Fixed in https://github.com/skyportal-contrib/skyportal-fink-client/commit/85f46acfc06152668b84b073f30b59d76de26575
